# Generated by Django 3.0.6 on 2021-04-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_create',
            field=models.DateField(auto_now=True),
        ),
    ]
