# Generated by Django 3.0.6 on 2021-04-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
